export interface Lot {
    id: number
    auction_id: number
    userid: number
    mainlotno: string
    consolLotIds: string
    wla_lotno: string
    users_for_auction_alert: string
    seller: string
    language: string
    price: string
    weightPrincple: string
    tagno: string
    lot_insurance: string
    game_capture_cost: string
    boma_type: string
    permit_cost: string
    transport_date: string
    delivery_cost: string
    free_kilometers: string
    province_id: string
    city_id: string
    description: string
    lot_image0: string
    lot_liveimage: string
    auction_status: string
    VMStatus: string
    status: string
    admin_status: string
    created_on: string
    sum_male: number
    sum_female: number
    sum_total: number
    sublot_type: string
    lottype: string
    Avg_wt_per_unit_Kg: number
    Actual_wt_per_unit_Kg: number
    Avg_wt_per_lot_Kg: number
    Actual_wt_per_lot_Kg: number
    lot_image1: string
    add_info_status: string
    start_time: string
    end_time: string
    lot_notes: string
    silent_interval: number
    incrementGroup: number
    targetPrice: number
    openingBid: number
    archive_status: string
}